<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NReco.PivotData" Version="1.5.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <Compile Include="../../AxialSqlTools/PivotGrid/PivotEngine.cs" Link="PivotEngine.cs" />
    <Compile Include="../../AxialSqlTools/PivotGrid/PivotPresentation.cs" Link="PivotPresentation.cs" />
    <Compile Include="../../AxialSqlTools/PivotGrid/PivotLayoutStore.cs" Link="PivotLayoutStore.cs" />
    <Compile Include="Program.cs" />
    <Compile Include="SettingsFileStoreStub.cs" />
  </ItemGroup>
</Project>
