<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NReco.PivotData" Version="1.5.1" />
    <Compile Include="../../AxialSqlTools/PivotGrid/PivotEngine.cs" Link="PivotEngine.cs" />
  </ItemGroup>
</Project>
