<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <ScriptDomVersion Condition="'$(ScriptDomVersion)' == ''">170.191.0</ScriptDomVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.SqlServer.TransactSql.ScriptDom" Version="$(ScriptDomVersion)" />
    <Compile Include="../../AxialSqlTools/Modules/TsqlFormatter.cs" Link="Production/TsqlFormatter.cs" />
    <Compile Include="../../AxialSqlTools/Modules/TsqlFormatterCommentInterleaver.cs" Link="Production/TsqlFormatterCommentInterleaver.cs" />
    <Compile Include="../../AxialSqlTools/Modules/TsqlSelectFieldIndentation.cs" Link="Production/TsqlSelectFieldIndentation.cs" />
  </ItemGroup>
</Project>
