<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.5.1"/>
    <Compile Include="../../AxialSqlTools/Modules/SQLBuilds.cs" Link="SQLBuilds.cs"/>
    <Compile Include="../../AxialSqlTools/Modules/SQLBuildsModels.cs" Link="SQLBuildsModels.cs"/>
  </ItemGroup>
</Project>
