<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <None Update="LegacyOutputCases.json" CopyToOutputDirectory="PreserveNewest" />
    <PackageReference Include="Microsoft.SqlServer.TransactSql.ScriptDom" Version="170.191.0" />
    <Compile Include="../../AxialSqlTools/Modules/SsmsFormatterReflection.cs" Link="SsmsFormatterReflection.cs" />
    <Compile Include="../../AxialSqlTools/Modules/TsqlFormatter.cs" Link="TsqlFormatter.cs" />
    <Compile Include="../../AxialSqlTools/Modules/TsqlFormatterCommentInterleaver.cs" Link="TsqlFormatterCommentInterleaver.cs" />
    <Compile Include="../../AxialSqlTools/Modules/TsqlSelectFieldIndentation.cs" Link="TsqlSelectFieldIndentation.cs" />
  </ItemGroup>
</Project>
