<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>7.3</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../AxialSqlTools/QuickSearch/QuickSearchNavigationTarget.cs" Link="QuickSearchNavigationTarget.cs" />
    <Compile Include="../../AxialSqlTools/Modules/ScriptObjectSelectionItem.cs" Link="ScriptObjectSelectionItem.cs" />
    <Compile Include="../../AxialSqlTools/Modules/ObjectExplorerPath.cs" Link="ObjectExplorerPath.cs" />
    <Compile Include="../../AxialSqlTools/Modules/ObjectExplorerNavigation.cs" Link="ObjectExplorerNavigation.cs" />
  </ItemGroup>
</Project>
